version: '3.3'
services:
  elasticsearch:
    image: elasticsearch:6.8.20
    container_name: elasticsearch
    hostname: elasticsearch
    volumes:
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    environment:
      - cluster.name=docker_cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 3
  
  kibana:
    image: kibana:6.8.20
    container_name: kibana
    hostname: kibana
    ports:
      - "5601:5601"
    links:
     - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    networks:
     - elk
    deploy:
      mode: replicated
      replicas: 1
  
  logstash:
    image: logstash:6.8.20
    container_name: logstash
    hostname: logstash
    volumes:
      - type: bind
        source: ./logstash/pipeline/logstash.conf
        target: /usr/share/logstash/pipeline/logstash.conf
      - type: bind
        source: ./logstash/input
        target: /usr/share/logstash/input
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf
    ports:
      - "9600:9600"
      - "5000:5000"
    depends_on:
      - elasticsearch
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1

networks:
  elk:
    driver: overlay

volumes:
  elasticsearch: