version: '3'
services:
  elasticsearch:
    image: elasticsearch:6.8.20
    container_name: elasticsearch
    hostname: elasticsearch
    volumes:
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    environment:
      - cluster.name=docker_cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk
  
  kibana:
    image: kibana:6.8.20
    container_name: kibana
    hostname: kibana
    ports:
      - "5601:5601"
    links:
     - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    networks:
     - elk
  
  logstash:
    image: logstash:6.8.20
    container_name: logstash
    hostname: logstash
    volumes:
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
      - type: bind
        source: ./logstash/input
        target: /usr/share/logstash/input
    ports:
      - "9600:9600"
      - "5044:5044"
    environment:
      - LS_JAVA_OPTS="-Xmx512m -Xmx512m"
    depends_on:
      - elasticsearch
    networks:
      - elk

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
